import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "PrayerTime",
  description: "Generated by create PrayerTime app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <main className="max-w-7xl mx-auto min-h-[calc(100vh-148px)] px-4 py-8">
          {children}
        </main>

        <footer className="bg-gray-800 text-white text-center py-4 mt-8">
          <p>&copy; {new Date().getFullYear()} PrayerTime App</p>
        </footer>
      </body>
    </html>
  );
}
